concurrent = 1
check_interval = 0
log_level = "debug"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "test"
  url = "https://192.168.253.131:2443/"
  token = "sPatAFQzs8xw6-LenJmH"
  tls-ca-file = "/etc/gitlab-runner/certs/192.168.253.131.crt"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "192.168.253.131:10051/mabo/docker_base:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock","/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
